import Head from 'next/head'
import {Divider} from 'antd'
import Headerslider from '../components/slider';
import FilmSlider from '../components/film-slider'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Headerslider />
        <Divider orientation="left">Top Films</Divider>
        <FilmSlider />
        <Divider orientation="left">Trending on Google</Divider>
        <FilmSlider />
        <Divider orientation="left">New movies</Divider>
        <FilmSlider />
      </div>

    </div>
  )
}
