import Head from 'next/head'
import {Divider} from 'antd'
import Headerslider from '../components/slider';
import FilmSlider from '../components/film-slider'
import FilmPoster from '../components/film-poster'
;


export default function Home() {  

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Headerslider />
        <Divider orientation="left"> <h5>Top Films</h5></Divider>
        <FilmSlider />
        <Divider orientation="left"> <h5>Trending on Google</h5></Divider>
        <FilmSlider dark/>
        <FilmPoster />
        <Divider orientation="left"><h5>New movies</h5></Divider>
        <FilmSlider />
      </div>
    </div>
  )
}

export async function getServerSideProps(context) {

  return {
    props: {
      
    },
  };
}

