import Head from 'next/head'
import Image from 'next/image'
import Headerslider from '../components/slider';
import FilmSlider from '../components/film-slider'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Headerslider />
        <FilmSlider />
      </div>

    </div>
  )
}
